#ifndef ANGLENATIVEINTERFACE_GLOBAL_H
#define ANGLENATIVEINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANGLENATIVEINTERFACE_LIBRARY)
#  define ANGLENATIVEINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANGLENATIVEINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANGLENATIVEINTERFACE_GLOBAL_H
